import { test } from "node:test";
import assert from "node:assert/strict";
import {
  extractJsonPayload,
  normalizeRunbookCommands,
  findBlockedCommand,
  loadBlockedCommands,
  buildRunbookScript,
  scriptFormatForPath,
  parseWindowsCdTarget,
} from "../src/runbook.js";

test("extractJsonPayload handles fenced, raw, and embedded JSON", () => {
  assert.deepEqual(extractJsonPayload('```json\n{"a":1}\n```'), { a: 1 });
  assert.deepEqual(extractJsonPayload('{"a":1}'), { a: 1 });
  assert.deepEqual(extractJsonPayload('prefix {"a":1} suffix'), { a: 1 });
  assert.equal(extractJsonPayload("no json at all"), null);
  assert.equal(extractJsonPayload(""), null);
});

test("normalizeRunbookCommands normalizes objects, strings, and notes", () => {
  const { commands, notes } = normalizeRunbookCommands({
    commands: [
      { description: "list", command: "ls -la" },
      "pwd",
      { title: "cmd alias", cmd: "whoami" },
      { description: "empty", command: "" },
      null,
    ],
    notes: ["be careful", ""],
  });
  assert.deepEqual(commands, [
    { description: "list", command: "ls -la" },
    { description: "", command: "pwd" },
    { description: "cmd alias", command: "whoami" },
  ]);
  assert.deepEqual(notes, ["be careful"]);
});

test("normalizeRunbookCommands is safe on malformed payloads", () => {
  assert.deepEqual(normalizeRunbookCommands(null), { commands: [], notes: [] });
  assert.deepEqual(normalizeRunbookCommands({}), { commands: [], notes: [] });
});

test("findBlockedCommand matches regex patterns and falls back to substrings", () => {
  const list = [
    { pattern: "\\brm\\s+-rf\\s+/(\\s|$)", reason: "destructive" },
    { pattern: "mkfs", reason: "formats disks" },
  ];
  assert.ok(findBlockedCommand("sudo rm -rf /", list));
  assert.ok(findBlockedCommand("mkfs.ext4 /dev/sda1", list));
  assert.equal(findBlockedCommand("ls -la", list), undefined);
});

test("the shipped blocklist catches known destructive commands", () => {
  const blocked = loadBlockedCommands();
  assert.ok(Array.isArray(blocked) && blocked.length > 0, "blocklist should load");
  assert.ok(findBlockedCommand("rm -rf /", blocked), "rm -rf / must be blocked");
  assert.ok(findBlockedCommand("rm -rf ~", blocked), "rm -rf ~ must be blocked");
  assert.equal(findBlockedCommand("echo hello", blocked), undefined);
});

test("scriptFormatForPath picks the format from the extension", () => {
  assert.equal(scriptFormatForPath("setup.sh"), "bash");
  assert.equal(scriptFormatForPath("setup"), "bash");
  assert.equal(scriptFormatForPath("Setup.PS1"), "powershell");
  assert.equal(scriptFormatForPath("setup.bat"), "batch");
  assert.equal(scriptFormatForPath("setup.cmd"), "batch");
});

test("buildRunbookScript writes a bash script with steps and notes", () => {
  const script = buildRunbookScript(
    [
      { description: "list files", command: "ls -la" },
      { description: "", command: "pwd" },
    ],
    ["check the output"],
    { format: "bash", title: "demo" }
  );
  assert.ok(script.startsWith("#!/usr/bin/env bash"));
  assert.ok(script.includes("set -euo pipefail"));
  assert.ok(script.includes("# Runbook: demo"));
  assert.ok(script.includes("# Step 1: list files"));
  assert.ok(script.includes("ls -la"));
  assert.ok(script.includes("# Step 2"));
  assert.ok(script.includes("# - check the output"));
});

test("buildRunbookScript comments out blocked commands", () => {
  const blockedList = [{ pattern: "mkfs", reason: "formats disks" }];
  const script = buildRunbookScript(
    [{ description: "format", command: "mkfs.ext4 /dev/sda1" }],
    [],
    { format: "bash", blockedList }
  );
  assert.ok(script.includes("# BLOCKED (formats disks)"));
  assert.ok(script.includes("# mkfs.ext4 /dev/sda1"));
  assert.ok(!/^mkfs/m.test(script), "blocked command must not appear uncommented");
});

test("buildRunbookScript emits powershell and batch headers", () => {
  const commands = [{ description: "", command: "dir" }];
  const ps1 = buildRunbookScript(commands, [], { format: "powershell" });
  assert.ok(ps1.includes('$ErrorActionPreference = "Stop"'));
  const bat = buildRunbookScript(commands, [], { format: "batch" });
  assert.ok(bat.startsWith("@echo off"));
  assert.ok(bat.includes("REM Generated by gac"));
});

test("parseWindowsCdTarget recognizes cd variants", () => {
  assert.equal(parseWindowsCdTarget("ls -la"), null);
  assert.deepEqual(parseWindowsCdTarget("cd"), { target: null });
  assert.deepEqual(parseWindowsCdTarget("cd projects"), { target: "projects" });
  assert.deepEqual(parseWindowsCdTarget("CD /d C:\\Users"), { target: "C:\\Users" });
  assert.deepEqual(parseWindowsCdTarget('cd "My Documents"'), { target: "My Documents" });
});
