// Consent statement, environment-override detection, and effective-decision
// computation. Pure functions only.

import {
  TELEMETRY_CONSENT_VERSION,
  TELEMETRY_DOCS_URL,
  PRIVACY_URL,
  ATTRIBUTION,
} from "./contract.js";

// The exact user-facing consent statement. Only minor terminal formatting may
// vary; the wording is fixed.
export const CONSENT_STATEMENT = `Optional telemetry

GAC can send privacy-preserving usage events to api.getgac.dev to help
prioritize features, understand active installations, and improve reliability.

When enabled, GAC sends:
- A random installation identifier generated by GAC. It is not based on
  your identity, account, hostname, hardware identifiers, or device identifiers.
  It allows events from the same GAC installation to be counted over time.
- GAC version, operating-system family, CPU architecture, and Node.js major version.
- Provider category: OpenAI-compatible, Ollama, Codex, or unknown.
- Action names, success/failure/cancel outcomes, operation timings, and
  coarse size or count buckets.
- Aggregate feature outcomes such as runbook steps run, skipped, edited,
  blocked, failed, or repaired.

GAC never sends prompts, model replies, chat content, system prompts,
commands, command output, files, paths, repository details, commit content,
model names, server URLs, configuration values, credentials, account details,
environment variables, hostnames, usernames, or device identifiers.

The telemetry service necessarily receives your source IP while processing
the HTTPS request, but the service is designed not to store it in its
telemetry database or application logs.

Telemetry is OFF by default.

Details: gac telemetry info
Status:  gac telemetry status
Enable:  gac telemetry enable
Disable: gac telemetry disable

Telemetry details: ${TELEMETRY_DOCS_URL}
Privacy policy:   ${PRIVACY_URL}

${ATTRIBUTION}`;

// Environment variables that, when affirmative, suppress telemetry.
export const ENV_SUPPRESSION_VARS = ["CI", "DO_NOT_TRACK", "DNT", "GAC_TELEMETRY_DISABLED"];

// Affirmative values are case-insensitive: 1, true, yes, on.
export function isAffirmative(value) {
  if (value === undefined || value === null) return false;
  const v = String(value).trim().toLowerCase();
  return v === "1" || v === "true" || v === "yes" || v === "on";
}

// Which suppression variables are currently affirmative. Returns
// { suppressed, reasons: [...var names...] }.
export function envSuppression(env = {}) {
  const reasons = [];
  for (const name of ENV_SUPPRESSION_VARS) {
    if (isAffirmative(env[name])) reasons.push(name);
  }
  return { suppressed: reasons.length > 0, reasons };
}

// Saved decision, honoring consent versioning. One of:
// "undecided" | "enabled" | "declined" | "disabled" | "consent-expired".
export function effectiveDecision(state) {
  if (!state || typeof state !== "object") return "undecided";
  if (state.decision === "enabled") {
    if (state.enabled !== true) return "undecided";
    if (state.consentVersion !== TELEMETRY_CONSENT_VERSION) return "consent-expired";
    if (!state.installationId) return "undecided";
    return "enabled";
  }
  if (state.decision === "declined") return "declined";
  if (state.decision === "disabled") return "disabled";
  return "undecided";
}

// Telemetry is effective only when consent is current AND no env override
// suppresses it.
export function isEffectivelyEnabled(state, env) {
  if (effectiveDecision(state) !== "enabled") return false;
  return !envSuppression(env).suppressed;
}

// The automatic one-time prompt fires only when the decision is undecided, the
// session is interactive, and no env override suppresses telemetry. It never
// fires for an expired consent — that path requires a manual `gac telemetry
// enable` (fail closed on a materially changed contract).
export function shouldAutoPrompt(state, env, { interactive } = {}) {
  if (!interactive) return false;
  if (envSuppression(env).suppressed) return false;
  return effectiveDecision(state) === "undecided";
}
