import terminalKit from "terminal-kit";
import { spawn } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";
import { chatCompletion } from "./gpt4all.js";
import { buildSystemPrompt } from "./prompts.js";
import { buildRunbookContext } from "./sysinfo.js";
import { promptInputLine, promptKeyAction } from "./tui.js";
import { attachInputToPrompt, formatFileContexts, truncateForContext } from "./input.js";
import {
  resolveContextWindow,
  resolveMaxTokens,
  contextBudget,
  estimateTokens,
} from "./contextwindow.js";
import {
  clampCount,
  countBucket,
  sizeBucket,
  exitCodeClass,
  inputMode,
} from "./telemetry/buckets.js";

const { terminal: term } = terminalKit;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BLOCKED_COMMANDS_PATH = path.resolve(__dirname, "../blocked_commands.json");

// ─────────────────────────────────────────────────────────────────
// Blocked-command guardrails
// ─────────────────────────────────────────────────────────────────

export function normalizeCommandText(value) {
  return String(value || "")
    .trim()
    .replace(/\s+/g, " ")
    .toLowerCase();
}

export function loadBlockedCommands() {
  try {
    const raw = fs.readFileSync(BLOCKED_COMMANDS_PATH, "utf8");
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed;
    if (parsed && Array.isArray(parsed.blocked)) return parsed.blocked;
    return [];
  } catch (err) {
    return [];
  }
}

export function findBlockedCommand(command, blockedList) {
  const raw = String(command || "");
  const normalized = normalizeCommandText(raw);
  return blockedList.find((entry) => {
    const patternText = String(entry.pattern || entry || "").trim();
    if (!patternText) return false;
    try {
      const regex = new RegExp(patternText, "i");
      if (regex.test(raw)) return true;
    } catch (err) {
      // Fall back to substring check if regex parsing fails.
    }
    const normalizedPattern = normalizeCommandText(patternText);
    return normalizedPattern && normalized.includes(normalizedPattern);
  });
}

// ─────────────────────────────────────────────────────────────────
// Model-response parsing
// ─────────────────────────────────────────────────────────────────

export function extractJsonPayload(text) {
  const trimmed = String(text || "").trim();
  if (!trimmed) return null;
  const fencedMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fencedMatch ? fencedMatch[1].trim() : trimmed;
  const firstBrace = candidate.indexOf("{");
  const lastBrace = candidate.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace === -1) return null;
  const jsonText = candidate.slice(firstBrace, lastBrace + 1);
  try {
    return JSON.parse(jsonText);
  } catch (err) {
    return null;
  }
}

export function normalizeRunbookCommands(payload) {
  if (!payload || !Array.isArray(payload.commands)) {
    return { commands: [], notes: [] };
  }
  const commands = payload.commands
    .map((item) => {
      if (typeof item === "string") {
        return { description: "", command: item };
      }
      if (!item || typeof item !== "object") return null;
      return {
        description: String(item.description || item.title || "").trim(),
        command: String(item.command || item.cmd || "").trim(),
      };
    })
    .filter((item) => item && item.command);
  const notes = Array.isArray(payload.notes)
    ? payload.notes.map((note) => String(note)).filter(Boolean)
    : [];
  return { commands, notes };
}

// ─────────────────────────────────────────────────────────────────
// Script export
// ─────────────────────────────────────────────────────────────────

export function scriptFormatForPath(exportPath) {
  const ext = path.extname(String(exportPath || "")).toLowerCase();
  if (ext === ".ps1") return "powershell";
  if (ext === ".bat" || ext === ".cmd") return "batch";
  return "bash";
}

export function buildRunbookScript(commands, notes, options = {}) {
  const { format = "bash", title = "", blockedList = [] } = options;
  const comment = format === "batch" ? "REM" : "#";
  const lines = [];

  if (format === "bash") {
    lines.push("#!/usr/bin/env bash");
  } else if (format === "batch") {
    lines.push("@echo off");
  }
  if (title) lines.push(`${comment} Runbook: ${title}`);
  lines.push(`${comment} Generated by gac. Review every command before running.`);
  if (format === "bash") {
    lines.push("set -euo pipefail");
  } else if (format === "powershell") {
    lines.push('$ErrorActionPreference = "Stop"');
  }
  lines.push("");

  commands.forEach((entry, index) => {
    if (entry.description) {
      lines.push(`${comment} Step ${index + 1}: ${entry.description}`);
    } else {
      lines.push(`${comment} Step ${index + 1}`);
    }
    const blocked = findBlockedCommand(entry.command, blockedList);
    if (blocked) {
      const reason = blocked.reason || "matches a guarded destructive pattern";
      lines.push(`${comment} BLOCKED (${reason}) - left commented out on purpose:`);
      lines.push(`${comment} ${entry.command}`);
    } else {
      lines.push(entry.command);
    }
    lines.push("");
  });

  if (notes.length) {
    lines.push(`${comment} Notes:`);
    notes.forEach((note) => lines.push(`${comment} - ${note}`));
    lines.push("");
  }

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────
// Command runner (persistent shell: bash/login shell on POSIX,
// PowerShell on Windows — cwd and environment persist across steps)
// ─────────────────────────────────────────────────────────────────

// Everything shell-specific lives in the spec: how to start the shell, what
// to run first, and which lines emit the exit-code marker after a command.
export function buildShellSpec(platform = os.platform()) {
  if (platform === "win32") {
    return {
      command: "powershell.exe",
      args: ["-NoLogo", "-NoProfile", "-Command", "-"],
      initLines: [],
      // $LASTEXITCODE is sticky across cmdlets, so reset it before each
      // command; the marker then reads $? for the command statement itself.
      preCommandLines: ["$global:LASTEXITCODE = 0"],
      statusLines: (token) => [
        "if ($?) { $__gac_status = if ($null -ne $LASTEXITCODE) { $LASTEXITCODE } else { 0 } } else { $__gac_status = 1 }",
        `Write-Output ("__GAC_EXIT__${token}__:" + $__gac_status + "__")`,
      ],
    };
  }
  return {
    command: process.env.SHELL || "bash",
    args: ["-l"],
    initLines: ["set -o pipefail"],
    preCommandLines: [],
    statusLines: (token) => [
      "__gac_status=$?",
      `printf "__GAC_EXIT__${token}__:%s__\\n" "$__gac_status"`,
    ],
  };
}

function createRunbookShell(spec) {
  const child = spawn(spec.command, spec.args, { stdio: "pipe" });
  const session = {
    child,
    spec,
    pending: null,
    closed: false,
  };

  const finalizePending = (result) => {
    if (!session.pending) return;
    const pending = session.pending;
    session.pending = null;
    pending.resolve(result);
  };

  const handleStdout = (data) => {
    const text = data.toString();
    const pending = session.pending;
    if (!pending) {
      term(text);
      return;
    }
    pending.buffer += text;
    let output = "";
    while (true) {
      const markerIndex = pending.buffer.indexOf(pending.marker);
      if (markerIndex === -1) {
        output += pending.buffer;
        pending.buffer = "";
        break;
      }
      output += pending.buffer.slice(0, markerIndex);
      const afterMarker = pending.buffer.slice(markerIndex + pending.marker.length);
      const endIndex = afterMarker.indexOf("__");
      if (endIndex === -1) {
        pending.buffer = pending.buffer.slice(markerIndex);
        break;
      }
      const exitCode = Number.parseInt(afterMarker.slice(0, endIndex), 10);
      pending.exitCode = Number.isNaN(exitCode) ? 1 : exitCode;
      pending.buffer = afterMarker.slice(endIndex + 2);
      pending.done = true;
    }
    if (output) {
      pending.stdout += output;
      term(output);
    }
    if (pending.done) {
      finalizePending({
        code: pending.exitCode ?? 0,
        stdout: pending.stdout,
        stderr: pending.stderr,
      });
    }
  };

  const handleStderr = (data) => {
    const text = data.toString();
    const pending = session.pending;
    if (pending) {
      pending.stderr += text;
    }
    term(text);
  };

  child.stdout.on("data", handleStdout);
  child.stderr.on("data", handleStderr);
  child.on("error", (err) => {
    const message = `Failed to start command: ${err.message}\n`;
    if (session.pending) {
      session.pending.stderr += message;
      finalizePending({ code: 1, stdout: session.pending.stdout, stderr: session.pending.stderr });
    }
    term(message);
    session.closed = true;
  });
  child.on("close", (code) => {
    session.closed = true;
    if (session.pending) {
      const message = `Shell session ended unexpectedly (exit code ${code ?? "unknown"}).\n`;
      session.pending.stderr += message;
      finalizePending({ code: code ?? 1, stdout: session.pending.stdout, stderr: session.pending.stderr });
      term(message);
    }
  });

  for (const line of spec.initLines) {
    child.stdin.write(`${line}\n`);
  }
  return session;
}

function closeRunbookShell(session) {
  if (!session || session.closed) return;
  session.child.stdin.end("exit\n");
}

function runShellCommand(session, command) {
  if (!session || session.closed) {
    return Promise.resolve({
      code: 1,
      stdout: "",
      stderr: "Shell session is not available.\n",
    });
  }
  return new Promise((resolve) => {
    const token = `gac_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    const marker = `__GAC_EXIT__${token}__:`;
    session.pending = {
      resolve,
      stdout: "",
      stderr: "",
      buffer: "",
      marker,
      done: false,
      exitCode: null,
    };
    for (const line of session.spec.preCommandLines) {
      session.child.stdin.write(`${line}\n`);
    }
    session.child.stdin.write(`${command}\n`);
    for (const line of session.spec.statusLines(token)) {
      session.child.stdin.write(`${line}\n`);
    }
  });
}

// Unified runner: one persistent shell session per runbook, so cd and
// environment variables persist across steps on every platform.
export function createCommandRunner() {
  const session = createRunbookShell(buildShellSpec());
  return {
    run: (command) => runShellCommand(session, command),
    close: () => closeRunbookShell(session),
  };
}

// ─────────────────────────────────────────────────────────────────
// Interactive flow
// ─────────────────────────────────────────────────────────────────

function printRunbookCommands(commands) {
  commands.forEach((entry, index) => {
    term(`${index + 1}. `);
    if (entry.description) {
      term(`${entry.description}\n   `);
    }
    term(`${entry.command}\n`);
  });
}

function printRemainingCommands(commands, startIndex) {
  if (startIndex >= commands.length) return;
  term("\nPlanned next commands:\n");
  commands.slice(startIndex).forEach((entry, offset) => {
    term(`${startIndex + offset + 1}. `);
    if (entry.description) {
      term(`${entry.description}\n   `);
    }
    term(`${entry.command}\n`);
  });
}

async function confirmRunbookStart() {
  const action = await promptKeyAction(
    "Press Enter to start running the runbook (q to cancel): ",
    { ENTER: "start", q: "cancel", Q: "cancel", ESCAPE: "cancel", CTRL_C: "cancel" }
  );
  return action === "start";
}

const QUIT_KEYS = { q: "quit", Q: "quit", ESCAPE: "quit", CTRL_C: "quit" };

// Per-step action prompt. Enter is disabled while the command matches a
// blocked pattern: it must be edited or skipped first.
function promptRunbookAction(isBlocked) {
  const keys = { e: "edit", E: "edit", s: "skip", S: "skip", ...QUIT_KEYS };
  if (isBlocked) {
    return promptKeyAction("[e] edit  [s] skip  [q] quit: ", keys);
  }
  return promptKeyAction("[Enter] run  [e] edit  [s] skip  [q] quit: ", {
    ENTER: "run",
    ...keys,
  });
}

function promptFailureAction() {
  return promptKeyAction(
    "[r] ask the model for a fix  [s] skip step  [q] stop runbook: ",
    { r: "fix", R: "fix", s: "skip", S: "skip", ...QUIT_KEYS }
  );
}

// Shape-check a {command, explanation} fix payload from the model. Shared
// with `gac fix`.
export function extractCommandFix(payload) {
  if (!payload || typeof payload !== "object") return null;
  const command = String(payload.command || payload.cmd || "").trim();
  if (!command) return null;
  return { command, explanation: String(payload.explanation || "").trim() };
}

function tail(text, maxChars) {
  const trimmed = String(text || "").trim();
  return trimmed.length > maxChars ? trimmed.slice(-maxChars) : trimmed;
}

// Ask the model for a corrected command after a step failed.
async function requestCommandFix(entry, result, config, telemetry) {
  const system = buildSystemPrompt("fix", config);
  const errorOutput = tail(result.stderr, 2000);
  const stdoutTail = tail(result.stdout, 1000);
  const user = [
    entry.description ? `Goal: ${entry.description}` : null,
    `This command failed with exit code ${result.code}:`,
    "```",
    entry.command,
    "```",
    errorOutput ? `Error output:\n\`\`\`\n${errorOutput}\n\`\`\`` : null,
    stdoutTail ? `Standard output (tail):\n\`\`\`\n${stdoutTail}\n\`\`\`` : null,
    "Provide the corrected command.",
  ]
    .filter(Boolean)
    .join("\n");
  const fixConfig = {
    ...config,
    stream: false,
    renderMarkdown: false,
    debugRender: false,
  };
  try {
    const reply = await chatCompletion(
      fixConfig,
      [
        { role: "system", content: system },
        { role: "system", content: `Relevant context:\n${buildRunbookContext()}` },
        { role: "user", content: user },
      ],
      { telemetry, telemetryAction: "runbook_self_heal" }
    );
    return extractCommandFix(extractJsonPayload(reply));
  } catch (err) {
    term.red(`Fix request failed: ${err.message}\n`);
    return null;
  }
}

async function editCommand(current) {
  const input = await promptInputLine("Edit command:\n> ", { default: String(current) });
  return input ? input : current;
}

async function requestRunbookPlan(prompt, config, opts) {
  const system = buildSystemPrompt("runbook", config);
  const contextWindow = await resolveContextWindow(config);
  const maxTokens = await resolveMaxTokens(config);
  const budgetChars = Math.max(
    4000,
    (contextBudget(contextWindow, maxTokens) - estimateTokens(system) - 500) * 4
  );

  const contextParts = [buildRunbookContext()];
  if (opts.files && opts.files.length) {
    contextParts.push(formatFileContexts(opts.files, Math.floor(budgetChars / (2 * opts.files.length))));
  }

  let userPrompt = prompt;
  if (opts.piped) {
    // Head+tail truncation, same as ask/explain — the end of a log is
    // usually where the error is.
    const { text: piped } = truncateForContext(opts.piped, Math.floor(budgetChars / 2));
    userPrompt = attachInputToPrompt(prompt, piped);
  }

  const messages = [
    { role: "system", content: system },
    { role: "system", content: `Relevant context:\n${contextParts.join("\n\n")}` },
    { role: "user", content: userPrompt },
  ];
  const runbookConfig = {
    ...config,
    stream: false,
    renderMarkdown: false,
    debugRender: false,
  };

  const reply = await chatCompletion(runbookConfig, messages, {
    contextWindow,
    telemetry: opts.telemetry,
    telemetryAction: "runbook_plan",
  });
  const payload = extractJsonPayload(reply);
  return normalizeRunbookCommands(payload);
}

export async function runRunbook(prompt, config, opts = {}) {
  const telemetry = opts.telemetry;
  // The run "mode" drives the plan/completed action names.
  const mode = opts.exportPath
    ? "export"
    : opts.dryRun
    ? "dry_run"
    : opts.interactive
    ? "execute"
    : "preview";

  const { commands, notes } = await requestRunbookPlan(prompt, config, opts);

  const blockedList = loadBlockedCommands();
  const blockedAtPlan = commands.filter((c) => findBlockedCommand(c.command, blockedList)).length;

  const planProps = {
    step_count: clampCount(commands.length),
    notes_present: notes.length > 0,
    blocked_step_count: clampCount(blockedAtPlan),
    input_mode: inputMode({
      hasArguments: Boolean(prompt && String(prompt).trim()),
      hasStdin: Boolean(opts.piped),
      hasFiles: Boolean(opts.files && opts.files.length),
    }),
    file_count_bucket: countBucket(opts.files ? opts.files.length : 0),
    prompt_size_bucket: sizeBucket(String(prompt || "").length),
  };
  const trackPlan = (outcome) => {
    if (!telemetry) return;
    telemetry.track({
      event_name: "runbook_plan_completed",
      action: mode,
      outcome,
      duration_ms: null,
      error_category: null,
      properties: planProps,
    });
  };

  // Per-run aggregate counters (all clamped 0–100 at emit time).
  const stats = {
    steps_total: commands.length,
    steps_run: 0,
    steps_succeeded: 0,
    steps_failed: 0,
    steps_skipped: 0,
    steps_edited: 0,
    blocked_encounters: 0,
    self_heal_requests: 0,
  };
  const trackRunbook = (outcome) => {
    if (!telemetry) return;
    telemetry.track({
      event_name: "runbook_completed",
      action: mode,
      outcome,
      duration_ms: null,
      error_category: null,
      properties: {
        steps_total: clampCount(stats.steps_total),
        steps_run: clampCount(stats.steps_run),
        steps_succeeded: clampCount(stats.steps_succeeded),
        steps_failed: clampCount(stats.steps_failed),
        steps_skipped: clampCount(stats.steps_skipped),
        steps_edited: clampCount(stats.steps_edited),
        blocked_encounters: clampCount(stats.blocked_encounters),
        self_heal_requests: clampCount(stats.self_heal_requests),
      },
    });
  };
  const trackStep = (action, outcome, extra = {}) => {
    if (!telemetry) return;
    const properties = {
      step_number: clampCount(extra.stepNumber ?? 0),
      step_count: clampCount(commands.length),
      was_blocked: Boolean(extra.wasBlocked),
    };
    if (extra.exitCodeClass !== undefined) properties.exit_code_class = extra.exitCodeClass;
    telemetry.track({
      event_name: "runbook_step_completed",
      action,
      outcome,
      duration_ms: null,
      error_category: extra.errorCategory ?? null,
      properties,
    });
  };

  if (!commands.length) {
    term("No runnable commands were returned. Try rephrasing your request.\n");
    trackPlan("no_op");
    trackRunbook("no_op");
    return { outcome: "no_op", props: {} };
  }

  term("Planned commands:\n");
  printRunbookCommands(commands);
  if (notes.length) {
    term("\nNotes:\n");
    notes.forEach((note) => term(`- ${note}\n`));
  }
  term("\n");

  if (opts.exportPath) {
    const format = scriptFormatForPath(opts.exportPath);
    const script = buildRunbookScript(commands, notes, {
      format,
      title: prompt,
      blockedList,
    });
    const resolved = path.resolve(process.cwd(), opts.exportPath);
    fs.writeFileSync(resolved, script, format === "bash" ? { mode: 0o755 } : undefined);
    term(`Runbook written to ${resolved}. Nothing was executed.\n`);
    trackPlan("success");
    trackRunbook("success");
    return { outcome: "success", props: {} };
  }

  if (opts.dryRun) {
    term("Dry run: no commands were executed.\n");
    trackPlan("success");
    trackRunbook("success");
    return { outcome: "success", props: {} };
  }

  if (!opts.interactive) {
    term(
      "Not an interactive terminal: showing the plan only. Use --export <path> to save it as a script.\n"
    );
    trackPlan("success");
    trackRunbook("success");
    return { outcome: "success", props: {} };
  }

  trackPlan("success");

  const ready = await confirmRunbookStart();
  if (!ready) {
    term("Runbook execution canceled.\n");
    trackRunbook("cancelled");
    return { outcome: "cancelled", props: {} };
  }

  const runner = createCommandRunner();
  for (let i = 0; i < commands.length; i += 1) {
    const entry = commands[i];
    const stepNumber = i + 1;

    term(`\nStep ${i + 1} of ${commands.length}:\n`);
    if (entry.description) {
      term(`${entry.description}\n`);
    }

    let stepDone = false;
    while (!stepDone) {
      let action;
      let wasBlocked = false;
      while (true) {
        term(`Command: ${entry.command}\n`);
        const blocked = findBlockedCommand(entry.command, blockedList);
        wasBlocked = Boolean(blocked);
        if (blocked) {
          stats.blocked_encounters += 1;
          term.red(
            `Blocked: ${blocked.reason || "matches a guarded destructive pattern"}\n`
          );
        }
        action = await promptRunbookAction(wasBlocked);
        if (action === "edit") {
          entry.command = await editCommand(entry.command);
          stats.steps_edited += 1;
          trackStep("edit", "success", { stepNumber, wasBlocked });
          continue;
        }
        break;
      }

      if (action === "skip") {
        term.dim(`Skipped step ${i + 1}.\n`);
        stats.steps_skipped += 1;
        trackStep("skip", "success", { stepNumber, wasBlocked });
        stepDone = true;
        continue;
      }
      if (action === "quit") {
        term(`Stopped at step ${i + 1}.\n`);
        printRemainingCommands(commands, i);
        trackStep("quit", "cancelled", { stepNumber, wasBlocked });
        runner.close();
        trackRunbook("cancelled");
        return { outcome: "cancelled", props: {} };
      }

      term(`\n$ ${entry.command}\n`);
      const result = await runner.run(entry.command);
      stats.steps_run += 1;
      if (result.code === 0) {
        term("\n");
        stats.steps_succeeded += 1;
        trackStep("run", "success", {
          stepNumber,
          wasBlocked,
          exitCodeClass: exitCodeClass(result.code),
        });
        stepDone = true;
        continue;
      }

      stats.steps_failed += 1;
      trackStep("run", "failure", {
        stepNumber,
        wasBlocked,
        exitCodeClass: exitCodeClass(result.code),
        errorCategory: "shell",
      });
      term(`\nCommand failed (step ${i + 1}) with exit code ${result.code}.\n`);
      if (result.stderr.trim()) {
        term(`Issue:\n${result.stderr}\n`);
      }
      const failureAction = await promptFailureAction();
      if (failureAction === "skip") {
        term.dim(`Skipping step ${i + 1}.\n`);
        stats.steps_skipped += 1;
        trackStep("skip", "success", { stepNumber, wasBlocked });
        stepDone = true;
        continue;
      }
      if (failureAction === "quit") {
        term(`Stopped at step ${i + 1}.\n`);
        printRemainingCommands(commands, i + 1);
        trackStep("quit", "cancelled", { stepNumber, wasBlocked });
        runner.close();
        trackRunbook("cancelled");
        return { outcome: "cancelled", props: {} };
      }
      // Self-heal: ask the model for a corrected command; it re-enters the
      // normal run/edit/skip gate (including the blocklist check) above.
      term.dim("Asking the model for a fix...\n");
      stats.self_heal_requests += 1;
      trackStep("self_heal_request", "success", { stepNumber, wasBlocked });
      const fix = await requestCommandFix(entry, result, config, telemetry);
      if (!fix) {
        term("No usable fix was returned.\n");
        trackStep("self_heal_result", "no_op", { stepNumber, wasBlocked });
        continue;
      }
      trackStep("self_heal_result", "success", { stepNumber, wasBlocked });
      if (fix.explanation) {
        term.dim(`Suggested fix: ${fix.explanation}\n`);
      }
      entry.command = fix.command;
    }
  }

  runner.close();
  term("All commands completed successfully.\n");
  trackRunbook("success");
  return { outcome: "success", props: {} };
}
