import terminalKit from "terminal-kit";
import { spawn } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";
import { chatCompletion } from "./gpt4all.js";
import { buildSystemPrompt } from "./prompts.js";
import { buildRunbookContext } from "./sysinfo.js";
import { attachInputToPrompt, formatFileContexts, truncateForContext } from "./input.js";
import {
  resolveContextWindow,
  contextBudget,
  estimateTokens,
} from "./contextwindow.js";

const { terminal: term } = terminalKit;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BLOCKED_COMMANDS_PATH = path.resolve(__dirname, "../blocked_commands.json");

// ─────────────────────────────────────────────────────────────────
// Blocked-command guardrails
// ─────────────────────────────────────────────────────────────────

export function normalizeCommandText(value) {
  return String(value || "")
    .trim()
    .replace(/\s+/g, " ")
    .toLowerCase();
}

export function loadBlockedCommands() {
  try {
    const raw = fs.readFileSync(BLOCKED_COMMANDS_PATH, "utf8");
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed;
    if (parsed && Array.isArray(parsed.blocked)) return parsed.blocked;
    return [];
  } catch (err) {
    return [];
  }
}

export function findBlockedCommand(command, blockedList) {
  const raw = String(command || "");
  const normalized = normalizeCommandText(raw);
  return blockedList.find((entry) => {
    const patternText = String(entry.pattern || entry || "").trim();
    if (!patternText) return false;
    try {
      const regex = new RegExp(patternText, "i");
      if (regex.test(raw)) return true;
    } catch (err) {
      // Fall back to substring check if regex parsing fails.
    }
    const normalizedPattern = normalizeCommandText(patternText);
    return normalizedPattern && normalized.includes(normalizedPattern);
  });
}

// ─────────────────────────────────────────────────────────────────
// Model-response parsing
// ─────────────────────────────────────────────────────────────────

export function extractJsonPayload(text) {
  const trimmed = String(text || "").trim();
  if (!trimmed) return null;
  const fencedMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fencedMatch ? fencedMatch[1].trim() : trimmed;
  const firstBrace = candidate.indexOf("{");
  const lastBrace = candidate.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace === -1) return null;
  const jsonText = candidate.slice(firstBrace, lastBrace + 1);
  try {
    return JSON.parse(jsonText);
  } catch (err) {
    return null;
  }
}

export function normalizeRunbookCommands(payload) {
  if (!payload || !Array.isArray(payload.commands)) {
    return { commands: [], notes: [] };
  }
  const commands = payload.commands
    .map((item) => {
      if (typeof item === "string") {
        return { description: "", command: item };
      }
      if (!item || typeof item !== "object") return null;
      return {
        description: String(item.description || item.title || "").trim(),
        command: String(item.command || item.cmd || "").trim(),
      };
    })
    .filter((item) => item && item.command);
  const notes = Array.isArray(payload.notes)
    ? payload.notes.map((note) => String(note)).filter(Boolean)
    : [];
  return { commands, notes };
}

// ─────────────────────────────────────────────────────────────────
// Script export
// ─────────────────────────────────────────────────────────────────

export function scriptFormatForPath(exportPath) {
  const ext = path.extname(String(exportPath || "")).toLowerCase();
  if (ext === ".ps1") return "powershell";
  if (ext === ".bat" || ext === ".cmd") return "batch";
  return "bash";
}

export function buildRunbookScript(commands, notes, options = {}) {
  const { format = "bash", title = "", blockedList = [] } = options;
  const comment = format === "batch" ? "REM" : "#";
  const lines = [];

  if (format === "bash") {
    lines.push("#!/usr/bin/env bash");
  } else if (format === "batch") {
    lines.push("@echo off");
  }
  if (title) lines.push(`${comment} Runbook: ${title}`);
  lines.push(`${comment} Generated by gac. Review every command before running.`);
  if (format === "bash") {
    lines.push("set -euo pipefail");
  } else if (format === "powershell") {
    lines.push('$ErrorActionPreference = "Stop"');
  }
  lines.push("");

  commands.forEach((entry, index) => {
    if (entry.description) {
      lines.push(`${comment} Step ${index + 1}: ${entry.description}`);
    } else {
      lines.push(`${comment} Step ${index + 1}`);
    }
    const blocked = findBlockedCommand(entry.command, blockedList);
    if (blocked) {
      const reason = blocked.reason || "matches a guarded destructive pattern";
      lines.push(`${comment} BLOCKED (${reason}) - left commented out on purpose:`);
      lines.push(`${comment} ${entry.command}`);
    } else {
      lines.push(entry.command);
    }
    lines.push("");
  });

  if (notes.length) {
    lines.push(`${comment} Notes:`);
    notes.forEach((note) => lines.push(`${comment} - ${note}`));
    lines.push("");
  }

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────
// Command runners (persistent POSIX shell / per-step Windows)
// ─────────────────────────────────────────────────────────────────

function createRunbookShell() {
  const shell = process.env.SHELL || "bash";
  const child = spawn(shell, ["-l"], { stdio: "pipe" });
  const session = {
    child,
    pending: null,
    closed: false,
  };

  const finalizePending = (result) => {
    if (!session.pending) return;
    const pending = session.pending;
    session.pending = null;
    pending.resolve(result);
  };

  const handleStdout = (data) => {
    const text = data.toString();
    const pending = session.pending;
    if (!pending) {
      term(text);
      return;
    }
    pending.buffer += text;
    let output = "";
    while (true) {
      const markerIndex = pending.buffer.indexOf(pending.marker);
      if (markerIndex === -1) {
        output += pending.buffer;
        pending.buffer = "";
        break;
      }
      output += pending.buffer.slice(0, markerIndex);
      const afterMarker = pending.buffer.slice(markerIndex + pending.marker.length);
      const endIndex = afterMarker.indexOf("__");
      if (endIndex === -1) {
        pending.buffer = pending.buffer.slice(markerIndex);
        break;
      }
      const exitCode = Number.parseInt(afterMarker.slice(0, endIndex), 10);
      pending.exitCode = Number.isNaN(exitCode) ? 1 : exitCode;
      pending.buffer = afterMarker.slice(endIndex + 2);
      pending.done = true;
    }
    if (output) {
      pending.stdout += output;
      term(output);
    }
    if (pending.done) {
      finalizePending({
        code: pending.exitCode ?? 0,
        stdout: pending.stdout,
        stderr: pending.stderr,
      });
    }
  };

  const handleStderr = (data) => {
    const text = data.toString();
    const pending = session.pending;
    if (pending) {
      pending.stderr += text;
    }
    term(text);
  };

  child.stdout.on("data", handleStdout);
  child.stderr.on("data", handleStderr);
  child.on("error", (err) => {
    const message = `Failed to start command: ${err.message}\n`;
    if (session.pending) {
      session.pending.stderr += message;
      finalizePending({ code: 1, stdout: session.pending.stdout, stderr: session.pending.stderr });
    }
    term(message);
    session.closed = true;
  });
  child.on("close", (code) => {
    session.closed = true;
    if (session.pending) {
      const message = `Shell session ended unexpectedly (exit code ${code ?? "unknown"}).\n`;
      session.pending.stderr += message;
      finalizePending({ code: code ?? 1, stdout: session.pending.stdout, stderr: session.pending.stderr });
      term(message);
    }
  });

  child.stdin.write("set -o pipefail\n");
  return session;
}

function closeRunbookShell(session) {
  if (!session || session.closed) return;
  session.child.stdin.end("exit\n");
}

function runShellCommand(session, command) {
  if (!session || session.closed) {
    return Promise.resolve({
      code: 1,
      stdout: "",
      stderr: "Shell session is not available.\n",
    });
  }
  return new Promise((resolve) => {
    const token = `gac_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    const marker = `__GAC_EXIT__${token}__:`;
    session.pending = {
      resolve,
      stdout: "",
      stderr: "",
      buffer: "",
      marker,
      done: false,
      exitCode: null,
    };
    session.child.stdin.write(`${command}\n`);
    session.child.stdin.write(`__gac_status=$?\n`);
    session.child.stdin.write(
      `printf "__GAC_EXIT__${token}__:%s__\\n" "$__gac_status"\n`
    );
  });
}

// `cd` needs special handling on Windows because each step runs in its own
// cmd.exe process, so directory changes would not stick otherwise.
export function parseWindowsCdTarget(command) {
  const trimmed = String(command || "").trim();
  // Compound or redirected commands (cd x && ..., cd x > out) must run in the
  // real shell; only a bare cd is simulated in-process for cwd persistence.
  if (/[&|<>]/.test(trimmed)) return null;
  const match = trimmed.match(/^cd(?:\s+\/d)?(?:\s+(.+))?$/i);
  if (!match) return null;
  let target = (match[1] || "").trim();
  if (
    target.length >= 2 &&
    ((target.startsWith('"') && target.endsWith('"')) ||
      (target.startsWith("'") && target.endsWith("'")))
  ) {
    target = target.slice(1, -1);
  }
  return { target: target || null };
}

function createWindowsRunner() {
  let cwd = process.cwd();

  const run = (command) => {
    const cd = parseWindowsCdTarget(command);
    if (cd) {
      if (!cd.target) {
        term(`${cwd}\n`);
        return Promise.resolve({ code: 0, stdout: `${cwd}\n`, stderr: "" });
      }
      const next = path.resolve(cwd, cd.target);
      try {
        if (fs.statSync(next).isDirectory()) {
          cwd = next;
          return Promise.resolve({ code: 0, stdout: "", stderr: "" });
        }
      } catch (err) {
        // Fall through to the not-found error below.
      }
      const message = `The system cannot find the path specified: ${next}\n`;
      term(message);
      return Promise.resolve({ code: 1, stdout: "", stderr: message });
    }

    return new Promise((resolve) => {
      let settled = false;
      const finish = (result) => {
        if (settled) return;
        settled = true;
        resolve(result);
      };
      let stdout = "";
      let stderr = "";
      const child = spawn(command, { shell: true, cwd, stdio: "pipe" });
      child.stdout.on("data", (data) => {
        const text = data.toString();
        stdout += text;
        term(text);
      });
      child.stderr.on("data", (data) => {
        const text = data.toString();
        stderr += text;
        term(text);
      });
      child.on("error", (err) => {
        const message = `Failed to start command: ${err.message}\n`;
        stderr += message;
        term(message);
        finish({ code: 1, stdout, stderr });
      });
      child.on("close", (code) => {
        finish({ code: code ?? 1, stdout, stderr });
      });
    });
  };

  return { run, close: () => {} };
}

// Unified runner: a persistent login shell on POSIX (so cd/env persist across
// steps), a per-step cmd.exe with tracked cwd on Windows. Windows limitation:
// environment variables set in one step do not carry into the next.
export function createCommandRunner() {
  if (os.platform() === "win32") {
    return createWindowsRunner();
  }
  const session = createRunbookShell();
  return {
    run: (command) => runShellCommand(session, command),
    close: () => closeRunbookShell(session),
  };
}

// ─────────────────────────────────────────────────────────────────
// Interactive flow
// ─────────────────────────────────────────────────────────────────

function printRunbookCommands(commands) {
  commands.forEach((entry, index) => {
    term(`${index + 1}. `);
    if (entry.description) {
      term(`${entry.description}\n   `);
    }
    term(`${entry.command}\n`);
  });
}

function printRemainingCommands(commands, startIndex) {
  if (startIndex >= commands.length) return;
  term("\nPlanned next commands:\n");
  commands.slice(startIndex).forEach((entry, offset) => {
    term(`${startIndex + offset + 1}. `);
    if (entry.description) {
      term(`${entry.description}\n   `);
    }
    term(`${entry.command}\n`);
  });
}

async function confirmRunbookStart(label) {
  term(label);
  return new Promise((resolve) => {
    term.grabInput({ mouse: "button" });
    const onKey = (name) => {
      term.grabInput(false);
      term.removeListener("key", onKey);
      term("\n");
      resolve(name === "ENTER");
    };
    term.on("key", onKey);
  });
}

// Per-step action prompt. Enter is disabled while the command matches a
// blocked pattern: it must be edited or skipped first.
async function promptRunbookAction(isBlocked) {
  if (isBlocked) {
    term.dim("[e] edit  [s] skip  [q] quit: ");
  } else {
    term.dim("[Enter] run  [e] edit  [s] skip  [q] quit: ");
  }
  return new Promise((resolve) => {
    term.grabInput({ mouse: "button" });
    const finish = (action) => {
      term.grabInput(false);
      term.removeListener("key", onKey);
      term("\n");
      resolve(action);
    };
    const onKey = (name) => {
      if (name === "ENTER" && !isBlocked) return finish("run");
      if (name === "e" || name === "E") return finish("edit");
      if (name === "s" || name === "S") return finish("skip");
      if (name === "q" || name === "Q" || name === "ESCAPE" || name === "CTRL_C") {
        return finish("quit");
      }
      // Ignore any other key so a stray keystroke can't run or abort a step.
    };
    term.on("key", onKey);
  });
}

async function editCommand(current) {
  term("Edit command:\n> ");
  return new Promise((resolve) => {
    term.inputField({ cancelable: true, default: String(current) }, (error, input) => {
      term("\n");
      if (error || input === undefined || input === null || !input.trim()) {
        resolve(current);
        return;
      }
      resolve(input.trim());
    });
  });
}

async function requestRunbookPlan(prompt, config, opts) {
  const system = buildSystemPrompt("runbook", config);
  const contextWindow = await resolveContextWindow(config);
  const budgetChars = Math.max(
    4000,
    (contextBudget(contextWindow, config.maxTokens) - estimateTokens(system) - 500) * 4
  );

  const contextParts = [buildRunbookContext()];
  if (opts.files && opts.files.length) {
    contextParts.push(formatFileContexts(opts.files, Math.floor(budgetChars / (2 * opts.files.length))));
  }

  let userPrompt = prompt;
  if (opts.piped) {
    // Head+tail truncation, same as ask/explain — the end of a log is
    // usually where the error is.
    const { text: piped } = truncateForContext(opts.piped, Math.floor(budgetChars / 2));
    userPrompt = attachInputToPrompt(prompt, piped);
  }

  const messages = [
    { role: "system", content: system },
    { role: "system", content: `Relevant context:\n${contextParts.join("\n\n")}` },
    { role: "user", content: userPrompt },
  ];
  const runbookConfig = {
    ...config,
    stream: false,
    renderMarkdown: false,
    debugRender: false,
  };

  const reply = await chatCompletion(runbookConfig, messages, { contextWindow });
  const payload = extractJsonPayload(reply);
  return normalizeRunbookCommands(payload);
}

export async function runRunbook(prompt, config, opts = {}) {
  const { commands, notes } = await requestRunbookPlan(prompt, config, opts);
  if (!commands.length) {
    term("No runnable commands were returned. Try rephrasing your request.\n");
    return;
  }

  const blockedList = loadBlockedCommands();

  term("Planned commands:\n");
  printRunbookCommands(commands);
  if (notes.length) {
    term("\nNotes:\n");
    notes.forEach((note) => term(`- ${note}\n`));
  }
  term("\n");

  if (opts.exportPath) {
    const format = scriptFormatForPath(opts.exportPath);
    const script = buildRunbookScript(commands, notes, {
      format,
      title: prompt,
      blockedList,
    });
    const resolved = path.resolve(process.cwd(), opts.exportPath);
    fs.writeFileSync(resolved, script, format === "bash" ? { mode: 0o755 } : undefined);
    term(`Runbook written to ${resolved}. Nothing was executed.\n`);
    return;
  }

  if (opts.dryRun) {
    term("Dry run: no commands were executed.\n");
    return;
  }

  if (!opts.interactive) {
    term(
      "Not an interactive terminal: showing the plan only. Use --export <path> to save it as a script.\n"
    );
    return;
  }

  const ready = await confirmRunbookStart(
    "Press Enter to start running the runbook (any other key to cancel): "
  );
  if (!ready) {
    term("Runbook execution canceled.\n");
    return;
  }

  const runner = createCommandRunner();
  for (let i = 0; i < commands.length; i += 1) {
    const entry = commands[i];

    term(`\nStep ${i + 1} of ${commands.length}:\n`);
    if (entry.description) {
      term(`${entry.description}\n`);
    }

    let action;
    while (true) {
      term(`Command: ${entry.command}\n`);
      const blocked = findBlockedCommand(entry.command, blockedList);
      if (blocked) {
        term.red(
          `Blocked: ${blocked.reason || "matches a guarded destructive pattern"}\n`
        );
      }
      action = await promptRunbookAction(Boolean(blocked));
      if (action === "edit") {
        entry.command = await editCommand(entry.command);
        continue;
      }
      break;
    }

    if (action === "skip") {
      term.dim(`Skipped step ${i + 1}.\n`);
      continue;
    }
    if (action === "quit") {
      term(`Stopped at step ${i + 1}.\n`);
      printRemainingCommands(commands, i);
      runner.close();
      return;
    }

    term(`\n$ ${entry.command}\n`);
    const result = await runner.run(entry.command);
    if (result.code !== 0) {
      term(
        `\nCommand failed (step ${i + 1}) with exit code ${result.code}. Stopping.\n`
      );
      if (result.stderr.trim()) {
        term(`Issue:\n${result.stderr}\n`);
      }
      printRemainingCommands(commands, i + 1);
      runner.close();
      return;
    }
    term("\n");
  }

  runner.close();
  term("All commands completed successfully.\n");
}
